# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.
# encoding: utf-8
require "logstash/outputs/base"
require "logstash/namespace"
require "logstash-output-elastic_apm_server_jars"
require "java"

class LogStash::Outputs::JavaOutputExample < LogStash::Outputs::Base
  config_name "elastic_apm_server"

  def self.javaClass() org.logstash.javaapi.ElasticApmServer.java_class; end
end
